apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
   name: pvc-grafana
   #labels:
   #  name: grafana
spec:    
   storageClassName: grafana-storage-class
   accessModes:
    - ReadWriteOnce
   resources:
    requests:   
      storage: 2Gi