apiVersion: v1

kind: PersistentVolume

metadata:
  name: pv-grafana
  labels:
    type: local

spec:
  storageClassName: grafana-storage-class
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/grafana"

  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sv-160-kb04