{
 "title": "Deployment Info",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Worker Node (Memória Total)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes / 1048576) by (instance) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Node (Memória Consumida)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"} / 1048576) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cordeiro", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Resource Limits (Memoria)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{image!=\"\", namespace=\"producao-cordeiro\", container!= \"\"} / 1048576) by(container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Resource Limits (Memória)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{image!=\"\", namespace=\"producao-cordeiro\", container!= \"\"} / 1048576)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Limits (CPU)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_quota{image!=\"\", namespace=\"producao-cordeiro\"} / 100) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Resource Limits (CPU)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_quota{image!=\"\", namespace=\"producao-cordeiro\"} / 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pádua", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Resource Limits (Memoria)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{image!=\"\", namespace=\"producao\", container!= \"\"} / 1048576) by(container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Resource Limits (Memória)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{image!=\"\", namespace=\"producao\", container!= \"\"} / 1048576)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Limits (CPU)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_quota{image!=\"\", namespace=\"producao\"} / 100) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Resource Limits (CPU)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_quota{image!=\"\", namespace=\"producao\"} / 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}