apiVersion: cert-manager.io/v1

kind: Certificate

metadata: 
  name: grafana-tls-padua
  
  
spec:
  commonName: grafana.padua.iff.edu.br
  secretName: cer-grafana-padua
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  
  dnsNames:
    - grafana.padua.iff.edu.br