apiVersion: v1

kind: PersistentVolume

metadata:
  name: pv-prometheus
  labels:
    type: local

spec:
  storageClassName: prometheus-storage-class
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  
  #salvo na máquina local
  hostPath:
    path: "/mnt/data/prometheus"


  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sv-160-kb04

