apiVersion: v1

kind: PersistentVolumeClaim

metadata: 
  name: pvc-prometheus
  #labels:
  #    name: prometheus
spec:  
  storageClassName: prometheus-storage-class  
  accessModes:
   - ReadWriteOnce
  resources:
   requests:   
     storage: 5Gi